Add search location

diff --git a/scripts/newmemo b/scripts/newmemo
--- a/scripts/newmemo
+++ b/scripts/newmemo
@@ -9,16 +9,23 @@ EOF
 exit 0
 fi
 
+if test -f '/mnt/c/Users/mpaulus/Command Commissioning/Library - Resources/Templates/ccllc-technical-memo-template.docx'; then
+    TEMPLATE='/mnt/c/Users/mpaulus/Command Commissioning/Library - Resources/Templates/ccllc-technical-memo-template.docx'
+elif test -f '/mnt/c/Users/mpaulus/Command Commissioning/Library - Documents/Resources/Templates/ccllc-technical-memo-template.docx'; then
+    TEMPLATE='/mnt/c/Users/mpaulus/Command Commissioning/Library - Documents/Resources/Templates/ccllc-technical-memo-template.docx'
+else
+    echo "Could not find the template file."
+    exit 1
+fi
+
 if test -n "$1"; then
-
     file_name="$*"
-
     case "$file_name" in
 
         *.docx)
-            cp '/mnt/c/Users/mpaulus/Command Commissioning/Library - Resources/Templates/ccllc-technical-memo-template.docx' "$file_name" ;;
+            cp "$TEMPLATE" "$file_name" ;;
         *)
-            cp '/mnt/c/Users/mpaulus/Command Commissioning/Library - Resources/Templates/ccllc-technical-memo-template.docx' "$file_name".docx ;;
+            cp "$TEMPLATE" "$file_name".docx ;;
     esac
 else
     printf "No file name passed.\n"
