Check that we actually have remind installed

diff --git a/scripts/random_remind b/scripts/random_remind
--- a/scripts/random_remind
+++ b/scripts/random_remind
@@ -1,9 +1,14 @@
 #!/bin/sh
 
+if ! command -v remind >/dev/null 2>&1; then
+    printf 'remind not found.\n'
+    exit 1
+fi
+
 first_reminder="$(remind ~/.config/remind/remind.rem | awk 'NR > 2 && $0 !~ /^ *$/' | shuf -n 1 | sed 's/ *$//')"
 
 if [ -n "$first_reminder" ]; then
-    printf '%s' "$first_reminder"
+    printf '%s\n' "$first_reminder"
 else
     printf "No reminders.\n"
 fi
