Clean up the shell syntax in tabula

diff --git a/scripts/tabula b/scripts/tabula
--- a/scripts/tabula
+++ b/scripts/tabula
@@ -1,20 +1,15 @@
 #!/bin/sh
 
 # Check for 'tabula.*jar' file in the LOCALBIN
+TABULA_JARS="$(find "$LOCALBIN" -name 'tabula*.jar' -type f)"
 
-if [ -f $LOCALBIN/tabula*.jar ]; then
+if [ -n "$TABULA_JARS" ]; then
     # Use the latest version if multiple
-    TABULA_JAR=`ls -1 $LOCALBIN/tabula*.jar | tail -1`
+    TABULA_JAR="$(echo "$TABULA_JARS" | sort -V | tail -n 1)"
 else
-    printf "ERROR: tabula.jar not found in %s\n" $LOCALBIN  >&2
-    exit 1
-fi
-
-# Check for 'java' command
-if [ -z `which java` ]; then
-    printf "ERROR: java command not found\n" >&2
+    printf "ERROR: tabula.jar not found in %s\n" "$LOCALBIN"  >&2
     exit 1
 fi
 
 # Run tabula.jar
-java -jar $TABULA_JAR --format TSV "$@"
+java -jar "$TABULA_JAR" "$@"
